export const generateMetadata = (
  title = "Supreme Auto Care",
  description = "Experience Detailing That Goes Above And Beyond Your Expectations"
) => {
  const metadataConfig = {
    title,
    description,
    url: "https://www.supremeautocare.ca/",
    image: "/icon.png",
    email: "abbosdetailing@gmail.com",
  };

  return {
    metadataBase: new URL(metadataConfig.url),
    robots: "follow, index",
    title: metadataConfig.title,
    description: metadataConfig.description,
    keywords: [
      "toronto",
      "scarborough",
      "detailing toronto",
      "detailing scarborough",
      "car detailing toronto",
      "car detailing scarborough",
      "ceramic coating",
      "ceramic coating toronto",
      "ceramic coating scarborough",
      "paint correction",
      "paint correction toronto",
      "paint correction scarborough",
      "luxury car detailing",
      "luxury car detailing toronto",
      "luxury car detailing scarborough",
      "high end car detailing",
      "high end car detailing toronto",
      "high end car detailing scarborough",
      "car wash toronto",
      "car wash scarborough",
      "car cleaning toronto",
      "car cleaning scarborough",
      "car waxing toronto",
      "car waxing scarborough",
      "toronto detailing",
      "scarborough detailing",
      "toronto car detailing",
      "scarborough car detailing",
      "auto detailing",
      "auto detailing toronto",
      "auto detailing scarborough",
      "mobile detailing",
      "mobile detailing toronto",
      "mobile detailing scarborough",
      "mobile car detailing",
      "mobile car detailing toronto",
      "mobile car detailing scarborough",
      "detailing",
      "car detailing", 
      "car wash", 
      "car cleaning", 
      "car waxing"
    ],
    openGraph: {
      type: "website",
      title: metadataConfig.title,
      locale: "en_CA",
      description: metadataConfig.description,
      url: metadataConfig.url,
      images: [
        { url: metadataConfig.image, width: 256, height: 256, alt: "favicon" },
      ],
    },
    twitter: {
      title: metadataConfig.title,
      description: metadataConfig.description,
      images: [
        { url: metadataConfig.image, width: 256, height: 256, alt: "favicon" },
      ],
    },
  };
};
