import Header from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Cinzel } from 'next/font/google'
import Footer from '@/components/footer'


const cinzel = Cinzel({ subsets: ['latin'] })
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <body className={cinzel.className}>{children}</body>
      <Footer />
    </html>
  )
}
